### ISSUE TITLE
Remove text on the circle visualisation 

### ISSUE THREAD

**Issue by adriangradinar** [larsmars/vuejs-progress-bar#17]
## Expected Behavior
On the circle progress bar, the value should not be displayed.

## Actual Behavior
The % value is displayed despite setting the parameter hideText to true

## Steps to Reproduce the Problem

  1. Implement default setup
  2. Set hideText to true
  3. Change type from line to circle

## Specifications

"vue": "^2.6.11",
 "vue-moment": "^4.1.0",
 "vuejs-progress-bar": "^1.2.0",

**Comment by adriangradinar** [comment]
Love your progress bar, absolutely brilliant. Took a while to find one as easy to implement as this one. Just this little niggle that I'd like to not display the value on the circle vis. Thanks!

**Comment by larsmars** [comment]
Thank you for the feedback 👍 this should now be fixed in v1.2.1

**Comment by adriangradinar** [comment]
Awesome, thanks! Loving it! Perfect for a weather gadget I was playing with. Cheers! Thank you,Adrian From: Lars MSent: 10 March 2020 16:14To: larsmars/vuejs-progress-barCc: adriangradinar; AuthorSubject: Re: [larsmars/vuejs-progress-bar] Remove text on the circle visualisation (#17) Thank you for the feedback 👍 this should now be fixed in v1.2.1—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
