### ISSUE TITLE
Class Name Conflict with Bootstrap

### ISSUE THREAD

**Issue by Petercopter** [larsmars/vuejs-progress-bar#26]
This plugin can't be used with the Bootstrap layout framework because there's a CSS class name conflict with `.progress-bar`. https://getbootstrap.com/docs/4.5/components/progress/

I was thinking about forking the repo and changing the class name to see if that fixes the problem, I can report back with how that goes. It looks like that might fix this issue as well: https://github.com/larsmars/vuejs-progress-bar/issues/6

**Comment by Kevin-DDR** [comment]
@Petercopter Hey! Any luck by changing the class name?

**Comment by larsmars** [comment]
Thank you for the feedback, this is now fixed in v1.2.3.
Closing this.
