### ISSUE TITLE
Circle progress not starting from top, and i didnt see anything about clockwise/conterclock wise

### ISSUE THREAD

**Issue by GreenRidingHood** [larsmars/vuejs-progress-bar#30]
hi

Can we decide clockwise/counter clockwise starting point. 
Also, is there anyway to setup starting point from top of the circle

this is happening if i set value 50 (assume this is 50%), but not starting from top
<img width="330" alt="Screen Shot 2021-01-14 at 11 09 48 AM" src="https://user-images.githubusercontent.com/17296724/104624361-14719c00-5659-11eb-837b-3154a76e8f48.png">

  - VueJS Version: vue@2.6.12

**Comment by larsmars** [comment]
Hi, thanks for the feedback. Inverted circle progress is now available (v1.2.5) 👍

**Comment by larsmars** [comment]
Circle progress now starts from top v1.2.7, closing
