### ISSUE TITLE
Help removing blue background

### ISSUE THREAD

**Issue by llhilton** [larsmars/vuejs-progress-bar#6]
I'd like to remove the blue background that is showing up, but I'm not sure why it's there.

Example:
![image](https://user-images.githubusercontent.com/3161805/42896766-edd330cc-8a8b-11e8-8339-339f95df56f8.png)

I am using this with Bootstrap-Vue, so I wonder if it's something that's coming in from there?

Options:
    progressOptions() {
            let color = 'orange';
            if(this.percentage < 30) {
                color = 'red';
            }
            if(this.percentage == 100) {
                color = '#2dbd2d';
            }
            let options = {
                text: {
                    hideText: true,
                },
                progress: {
                    color: color,
                    backgroundColor: '#C0C0C0'
                },
                layout: {
                    type: 'cylinder',
                    width: '100%',
                    height: 15,
                },
            }
            return options;
        },

Template code:
    <b-row class="mb-2" >
                <b-col cols="12">
                    <progress-bar :options="progressOptions" :value="percentage" />
                </b-col>
            </b-row>

**Comment by larsmars** [comment]
Hi, for color code use hex or rgb as described in the readme file. (ie. orange = #FFA500)

The blue color you have in the background come from somewhere else. Use dev tools in your browser to find/track down what gives you this blue color. It's impossible for me to say without seeing the code.

You can use this as referance: https://softwarefun.no/#/progressbar
