### ISSUE TITLE
Width as %

### ISSUE THREAD

**Issue by llhilton** [larsmars/vuejs-progress-bar#7]
I'd like to set the width of the bar to be 100% of the container it's in. I've tried setting the width to 100%, but that doesn't do anything. 

I suppose I could try and get the width dynamically, but that's currently beyond my css/javascript knowledge.

Thanks!

**Comment by larsmars** [comment]
Hi, this would have been cool. It is a little hard to get the SVG rendering propositional in x and y direction just using 100% width and with no hard X and Y numbers. I have done some experiments with medium success. It is located on back burner :)

**Comment by chrislebaron** [comment]
You can hack your way around this if you put a "ref" on the parent div like so:
```
<div ref="parent">
    <progress-bar
                v-if="options.layout.width > 0"
                :value="value"
                :options="options"
        />
</div>
```

Then in your `mounted` hook just add something like this to calculate the width:
```
this.options.layout.width = parseInt(this.$refs.parent.offsetWidth * .9)
```
Not pretty, but it works.

**Comment by olasunkanmi04** [comment]
If anyone is still having this problem, you can simply fix it from the css

> scss

```
.vuejs-progress-bar {
        width: 100% !important;

        #line-progress {
          width: 100% !important;
        }
      }
```
